# Generated by Django 4.0.2 on 2022-03-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='goodsspecification',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='skuimage',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='goodschannel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='goodschannel',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='specificationoption',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='specificationoption',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='specificationoption',
            name='update_time',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsSpecification',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.DeleteModel(
            name='SKUImage',
        ),
    ]
